"use client";

import { ChevronDown } from "lucide-react";

import type { ActivityScore } from "@/lib/weather/scores";

/**
 * Activity scores.
 *
 * These are this application's recommendations, not measurements, and they say
 * so plainly. Each one opens to show every deduction that produced it — a
 * score you cannot interrogate is just an opinion with a number attached, and
 * the whole point is that these are checkable.
 */

export function ScoreRow({ scores }: { scores: ActivityScore[] }) {
  return (
    <div className="flex flex-col gap-2">
      <ul className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        {scores.map((score) => (
          <li key={score.id}>
            <details className="group h-full">
              <summary className="flex cursor-pointer list-none flex-col gap-1.5 rounded-md border border-hairline p-3 transition-colors hover:border-strong">
                <span className="flex items-baseline justify-between gap-2">
                  <span className="label-micro">{score.label}</span>
                  <ChevronDown
                    className="size-3.5 shrink-0 text-tertiary transition-transform group-open:rotate-180"
                    aria-hidden
                  />
                </span>

                <span className="flex items-baseline gap-1">
                  <span className="readout text-xl">{score.score}</span>
                  <span className="text-[10px] text-tertiary">/100</span>
                </span>

                <span className="text-xs text-secondary">{score.rating}</span>

                {/* A bar as well as a number, so the comparison across the row
                    is visible without reading four figures. */}
                <span
                  aria-hidden
                  className="mt-1 block h-1 rounded-full bg-[--surface-hover]"
                >
                  <span
                    className="block h-full rounded-full bg-primary"
                    style={{ width: `${score.score}%` }}
                  />
                </span>
              </summary>

              <div className="mt-2 rounded-md border border-hairline bg-sunken p-3">
                <p className="text-xs leading-relaxed text-secondary">
                  {score.summary}
                </p>

                {score.factors.length > 0 ? (
                  <dl className="mt-3 flex flex-col gap-2 border-t border-hairline pt-3">
                    {score.factors.map((factor) => (
                      <div key={factor.label} className="flex flex-col gap-0.5">
                        <div className="flex items-baseline justify-between gap-3">
                          <dt className="text-xs">{factor.label}</dt>
                          <dd className="measured text-xs text-tertiary">
                            −{factor.penalty}
                          </dd>
                        </div>
                        <p className="text-[11px] leading-relaxed text-tertiary">
                          {factor.note}
                        </p>
                      </div>
                    ))}
                  </dl>
                ) : (
                  <p className="mt-2 text-[11px] text-tertiary">
                    Nothing was deducted.
                  </p>
                )}
              </div>
            </details>
          </li>
        ))}
      </ul>

      <p className="text-[11px] leading-relaxed text-tertiary">
        Scores are generated by ISOBAR from forecast data using the rules shown
        above. They are recommendations, not official meteorological guidance.
      </p>
    </div>
  );
}
