"use client";

import { ExternalLink, ShieldCheck } from "lucide-react";

import { SeverityMark } from "@/components/alerts/SeverityMark";
import { DetailRow, Panel, SectionHeading } from "@/components/ui/primitives";
import { usePreferences } from "@/lib/stores/preferences";
import { describeLocation } from "@/lib/locations/places";
import { formatFull } from "@/lib/time";
import { SEVERITY } from "@/lib/weather/scales";
import type { WeatherAlert } from "@/types/alerts";
import type { GeoLocation } from "@/types/location";
import type { Degradation } from "@/types/weather";

/**
 * The severe weather centre.
 *
 * Alerts are the most consequential thing this product shows, so the design is
 * deliberately plain: full text, no truncation, no interaction needed to read
 * what an agency actually said. Official bulletins and this application's own
 * derived advisories are separated and labelled, because conflating them would
 * borrow authority we do not have.
 */

export function AlertCenter({
  alerts,
  location,
  derivedOnly,
  degraded,
}: {
  alerts: WeatherAlert[];
  location: GeoLocation;
  derivedOnly: boolean;
  degraded?: Degradation;
}) {
  const hour12 = usePreferences((store) => store.hour12);

  const official = alerts.filter((alert) => alert.origin === "official");
  const derived = alerts.filter((alert) => alert.origin === "derived");

  return (
    <div className="flex flex-col gap-5">
      <header className="flex flex-col gap-1">
        <h1 className="text-lg font-semibold tracking-tight">Weather alerts</h1>
        <p className="text-xs text-tertiary">{describeLocation(location)}</p>
      </header>

      {degraded ? (
        <Panel surface="sunken" className="p-4">
          <p className="text-sm">{degraded.message}</p>
        </Panel>
      ) : null}

      {alerts.length === 0 ? (
        <Panel className="flex flex-col items-start gap-3 p-8">
          <ShieldCheck className="size-6 text-tertiary" aria-hidden />
          <p className="text-sm font-medium">No alerts in force</p>
          <p className="max-w-prose text-xs leading-relaxed text-tertiary">
            Nothing in the forecast for {location.name} crosses an advisory
            threshold, and no agency has issued a warning for this area.
            {derivedOnly
              ? " No open official feed covers this country, so advisories here are derived from forecast data."
              : ""}
          </p>
        </Panel>
      ) : null}

      {official.length > 0 ? (
        <section className="flex flex-col gap-3">
          <SectionHeading
            title="Official warnings"
            detail={`${official.length} in force`}
          />
          {official.map((alert) => (
            <AlertCard key={alert.id} alert={alert} timezone={location.timezone} hour12={hour12} />
          ))}
        </section>
      ) : null}

      {derived.length > 0 ? (
        <section className="flex flex-col gap-3">
          <SectionHeading
            title="Derived advisories"
            detail="Generated by ISOBAR from forecast data"
          />
          <p className="max-w-prose text-xs leading-relaxed text-tertiary">
            These are not issued by a meteorological agency. They are computed
            from the same forecast shown elsewhere in this app, against the
            documented thresholds shown on each card.
          </p>
          {derived.map((alert) => (
            <AlertCard key={alert.id} alert={alert} timezone={location.timezone} hour12={hour12} />
          ))}
        </section>
      ) : null}
    </div>
  );
}

function AlertCard({
  alert,
  timezone,
  hour12,
}: {
  alert: WeatherAlert;
  timezone: string;
  hour12: boolean;
}) {
  const style = SEVERITY[alert.severity];

  return (
    <Panel
      asChild
      className="overflow-hidden"
      // A solid rule in the severity colour, alongside the mark and the written
      // level — three channels, so none of them has to carry it alone.
      style={{ borderLeftWidth: 3, borderLeftColor: style.color }}
    >
      <article className="flex flex-col gap-4 p-5">
        <div className="flex items-start gap-3">
          <SeverityMark severity={alert.severity} className="mt-0.5" />
          <div className="flex min-w-0 flex-1 flex-col gap-1">
            <h2 className="text-base font-semibold leading-snug">{alert.headline}</h2>
            <p className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-tertiary">
              <span className="font-medium uppercase tracking-wider">{style.label}</span>
              <span aria-hidden>·</span>
              <span>{alert.source}</span>
            </p>
          </div>
        </div>

        <dl className="border-y border-hairline py-1">
          <DetailRow
            label="In force"
            value={
              <>
                {formatFull(alert.effective, timezone, hour12 ? "en-US" : "en-GB")}
                {alert.expires
                  ? ` — ${formatFull(alert.expires, timezone, hour12 ? "en-US" : "en-GB")}`
                  : ""}
              </>
            }
          />
          {alert.areas.length > 0 ? (
            <DetailRow label="Affected area" value={alert.areas.slice(0, 4).join(", ")} />
          ) : null}
        </dl>

        {alert.description ? (
          <div className="flex flex-col gap-1.5">
            <p className="label-micro">What to expect</p>
            <p className="max-w-prose whitespace-pre-line text-sm leading-relaxed text-secondary">
              {alert.description}
            </p>
          </div>
        ) : null}

        {alert.instruction ? (
          <div className="flex flex-col gap-1.5">
            <p className="label-micro">Recommended action</p>
            <p className="max-w-prose whitespace-pre-line text-sm leading-relaxed text-secondary">
              {alert.instruction}
            </p>
          </div>
        ) : null}

        {alert.basis ? (
          <details className="text-xs">
            <summary className="cursor-pointer text-tertiary hover:text-secondary">
              How this advisory was determined
            </summary>
            <p className="mt-2 max-w-prose leading-relaxed text-tertiary">{alert.basis}</p>
          </details>
        ) : null}

        {alert.url ? (
          <a
            href={alert.url}
            target="_blank"
            rel="noreferrer noopener"
            className="inline-flex w-fit items-center gap-1.5 text-xs text-secondary underline underline-offset-4 hover:text-primary"
          >
            Read the full bulletin
            <ExternalLink className="size-3" aria-hidden />
          </a>
        ) : null}
      </article>
    </Panel>
  );
}
